### ISSUE TITLE
Mac Drag & Drop Build

### ISSUE THREAD

**Issue by maxoakland** [bbbbbr/romusage#11]
I see there's a Windows Drag & Drop build. Will you make a Mac drag & drop build too?

**Comment by bbbbbr** [comment]
The drag-and-drop mode relies on special behavior of the windows UI that automatically runs terminal app drop targets as a program and passes the filename of the dropped item as a standard shell argument.

Did some reading and so far I haven't found an equivalent feature or way to do this for MacOS (same for Linux for that matter). Unfortunately I don't have much dev experience or knowledge about MacOS. romusage happens to build and work ont hat platform since there is a unix like environment for it to run on (the WIndows build uses mingw to achieve that).

So closing this for now as not implementable, but if someone came along with more knowledge and had an idea about how to do it I'd be open to supporting it.

**Comment by maxoakland** [comment]
Thanks for the effort you put into it!
