### ISSUE TITLE
NES support

### ISSUE THREAD

**Issue by hbons** [bbbbbr/romusage#13]
Is NES support on the roadmap? This would be super helpful for me. :)

**Comment by bbbbbr** [comment]
I don't have plans right now, but if it's possible to add without major changes to the program I'm open to it.

- One of the main things is that I don't have an understanding of the NES memory map and what it's ranges and limitations are due to lack of familiarity with the system.
- For SMS/GG some gbdk-specific assumptions are made about memory layout that aren't general to all SMS/GG ROMs. This might be the case for NES as well.

For example, here are the memory templates that are used for GB and SMS/GG:
https://github.com/bbbbbr/romusage/blob/main/src/bank_templates.c#L37C1-L77C160

@michel-iwaniec If you think this is plausible based on how gbdk-NES support is set up and you're interested in giving an overview of the memory config then let me know. I also understand that you're pretty busy with your project right now.

**Comment by bbbbbr** [comment]
Michel provided some guidance.
Here's an experimental build you can test and share feedback on (`platform/nes` branch).
https://github.com/bbbbbr/romusage/actions/runs/11906722260

You'll need to set the `-p:NES` flag and then use a .noi or .map file

**Comment by bbbbbr** [comment]
![romusage_nes_test_autobank_example](https://github.com/user-attachments/assets/3b0dc437-56c8-4b59-b1d2-f0cc13f7769a)

**Comment by hbons** [comment]
Wow that's blazingly fast turnaround! :)

Compiled romusage from source and It seems to work fine. The 27% used looks credible for my game at this point:

<img width="984" alt="Screenshot 2024-11-19 at 14 17 45" src="https://github.com/user-attachments/assets/5e64aaa1-b5f4-4c07-a35e-54a5dbe87a4e">

**Comment by bbbbbr** [comment]
Great, considering it was pretty straightforward and haven't seen major quirks I'll merge NES support into main. Closing the ticket, but feel free to comment here.
